### ISSUE TITLE
Pointer cursor while hovering over a Chat card

### ISSUE THREAD

**Issue by karmek-k** [korero-chat/web-client#4]
![pointing cursor](https://static.thenounproject.com/png/2030-200.png)
This cursor should appear while hovering over a chat card.
`src/pages/components-dashboard/ChatCard.js`

**Comment by Nakius2137** [comment]
biorę

**Comment by karmek-k** [comment]
Already done. 
Commit hash: 5764bdc465230906155074b181204e1e18beb712
